name: Fhi.ClientCredentialsKeypairs.Nuget

on:
  push:
    branches:
      - main
    paths:
      - 'Fhi.ClientCredentialsKeypairs/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
defaults:
  run:
    shell: pwsh
    working-directory: ./Fhi.ClientCredentialsKeypairs

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Pack
        run: dotnet pack --output package

      - name: Publish nupkg and snupkg to NuGet.org
        run: |
          foreach($file in (Get-ChildItem -Path package -Recurse -Include "*.nupkg")) {
              Write-Host "Publishing nupkg and snupkg:: " $file.FullName
              dotnet nuget push $file.FullName --api-key "${{ secrets.NUGET_ORG_FHI_PUBLISH }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
